/** @type {import("prettier").Config} */
module.exports = {
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
  pluginSearchDirs: false,
  importOrder: [
    "^react",
    "^next/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@env/(.*)$",
    "^@lib/(.*)$",
    "",
    "^@server/(.*)$",
    "",
    "^@hooks/(.*)$",
    "^@context/(.*)$",
    "^@utils/(.*)$",
    "",
    "^@cms/(.*)$",
    "",
    "^@layout/(.*)$",
    "",
    "^@components/(.*)$",
    "",
    "^@styles/(.*)$",
    "",
    "^[./]",
  ],
  importOrderBuiltinModulesToTop: true,
  importOrderCaseInsensitive: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
